CREATE TABLE game_release (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    release_date DATE NOT NULL,
    platform VARCHAR(100)
);

CREATE INDEX idx_game_release_release_date ON game_release (release_date);
